---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "preparebet"
description: Prepare anatomical images for brain extraction with BET
keywords:
  - volume
  - mask
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - anat:
      type: list
      description: Anat Nifti image
      pattern: "*.{nii,nii.gz}"


output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@EliseCos"